# Generated by Django 4.0.5 on 2022-06-09 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_tweetdata_id_alter_tweetdata_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweetdata',
            options={'ordering': ['-text'], 'verbose_name_plural': 'Tweetdata'},
        ),
        migrations.RenameField(
            model_name='tweetdata',
            old_name='name',
            new_name='text',
        ),
    ]
