# Generated by Django 4.0.5 on 2022-06-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_tweetdata_options_rename_name_tweetdata_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetdata',
            name='tweet_id',
            field=models.IntegerField(default=3, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tweetdata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
