# Generated by Django 4.0.5 on 2022-06-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_tweetdata_tweet_id_alter_tweetdata_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweetdata',
            name='tweet_id',
        ),
        migrations.AlterField(
            model_name='tweetdata',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
