# Generated by Django 4.0.5 on 2022-06-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_tweetdata_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetdata',
            name='public_metrics',
            field=models.JSONField(default={}),
        ),
    ]
