# Generated by Django 4.0.5 on 2022-06-13 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_tweetdata_public_metrics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweetdata',
            name='public_metrics',
        ),
        migrations.AddField(
            model_name='tweetdata',
            name='likes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
