# Generated by Django 4.0.5 on 2022-06-15 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_tweetdata_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweetdata',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Tweetdata'},
        ),
    ]
