# Generated by Django 4.0.5 on 2022-06-17 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_tweetdata_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweetdata',
            options={'ordering': ['-updated_at'], 'verbose_name_plural': 'Tweetdata'},
        ),
    ]
